// Prints research-pace, war, and victory numbers for an all-AI 5-civ game on the report seeds.
// Run: npm run sim   (TURNS=150 npm run sim for a shorter run)
import { it } from 'vitest';
import { simulate, medianTurn, report } from '../src/dev/sim';
import { landmassStats } from '../src/dev/landmass';
it('report', () => {
  const seeds = [8, 13, 21, 33, 42];
  const turns = Number(process.env.TURNS ?? 300);
  const all: any[] = [];
  let wars = 0, peace = 0, elim = 0, overseas = 0, landings = 0;
  const ships100: number[] = [], ships200: number[] = [];
  const seedTree: number[] = [];
  const wins: string[] = [];
  const barbs: any[] = [];
  const gp150: number[] = [];
  const air220: number[] = [];
  let strikes = 0, intercepts = 0, captures = 0;
  const religionsPerGame: number[] = [];
  let followers150 = 0, cities150 = 0, missionaries = 0, missionaryConv = 0, conversions = 0;
  const roads100: number[] = [], roads200: number[] = [];
  const earliestWin: number[] = [];
  for (const seed of seeds) {
    const t0 = Date.now();
    const r = simulate(seed, turns);
    wars += r.warsDeclared; peace += r.peaceTreaties; elim += r.eliminated;
    const line = r.civs.map((c) => `${c.civId}:M${c.eraTurn.medieval ?? '-'}/I${c.eraTurn.industrial ?? '-'}/Mo${c.eraTurn.modern ?? '-'}/done${c.treeDoneTurn ?? '-'} t50=${c.techsAt[50]} t100=${c.techsAt[100]} t150=${c.techsAt[150]} t200=${c.techsAt[200]} t250=${c.techsAt[250]} c=${c.cities}`).join('\n  ');
    const v = r.victory;
    const win = v ? `${r.state.players[v.winner]!.civId} ${v.kind} t${v.turn}` : 'none';
    wins.push(`seed ${seed}: ${win}`);
    const ends = r.state.players.filter((q) => q.kind !== 'barbarian').map((q) => `${q.civId}:${r.goals[q.id]} cul=${q.culture} gold=${q.gold} sci=${q.scienceRate} parts=${q.space.parts} arrives=${q.space.arrivesTurn ?? '-'} wonders=${r.state.cities.filter((c) => c.owner === q.id).reduce((n, c) => n + c.wonders.length, 0)}`).join('\n  ');
    report(`seed ${seed} (${Date.now()-t0}ms) wars=${r.warsDeclared} peace=${r.peaceTreaties} elim@120=${r.eliminated} VICTORY=${win}\n  ${line}\n  ${ends}`);
    const naval = r.civs.map((c) => `${c.civId}:overseas=${c.overseasCities} ships@100=${c.shipsAt[100] ?? '-'} ships@200=${c.shipsAt[200] ?? '-'}`).join(' ');
    report(`  NAVAL landings=${r.landings} ${naval}`);
    overseas += r.civs.reduce((a, c) => a + c.overseasCities, 0);
    landings += r.landings;
    ships100.push(...r.civs.map((c) => c.shipsAt[100] ?? 0));
    ships200.push(...r.civs.map((c) => c.shipsAt[200] ?? 0));
    all.push(...r.civs);
    barbs.push(r.barbarians);
    gp150.push(...r.civs.map((c) => c.greatPeopleAt[150] ?? 0));
    air220.push(...r.civs.map((c) => c.aircraftAt[220] ?? 0));
    strikes += r.strikes; intercepts += r.intercepts; captures += r.captures;
    report(`  AIR strikes=${r.strikes} intercepts=${r.intercepts} captures=${r.captures} aircraft@220 ${r.civs.map((c) => `${c.civId}:${c.aircraftAt[220] ?? '-'}`).join(' ')}`);
    const b = r.barbarians;
    report(`  BARBARIANS villages=${b.villagesAtStart} destroyed=${b.villagesDestroyed} settled=${b.villagesSettled} spawned=${b.spawned} killed=${b.killed} raids=${b.raids} elimByBarb=${b.eliminationsByBarbarians} huts=${b.hutsEntered} artifacts=${b.artifacts}; GP@150 ${r.civs.map((c) => `${c.civId}:${c.greatPeopleAt[150] ?? '-'}`).join(' ')}`);
    seedTree.push(Math.min(...r.civs.map((c) => c.treeDoneTurn ?? Infinity)));
    // Round 12: religion and roads.
    const rel = r.religion;
    religionsPerGame.push(rel.founded.length);
    followers150 += rel.followersAt150; cities150 += rel.citiesAt150;
    missionaries += rel.missionaries; missionaryConv += rel.missionaryConversions; conversions += rel.conversions;
    roads100.push(...r.civs.map((c) => c.roadsAt[100] ?? 0));
    roads200.push(...r.civs.map((c) => c.roadsAt[200] ?? 0));
    if (r.victory) earliestWin.push(r.victory.turn);
    report(`  RELIGION founded ${rel.founded.map((f) => `${f.name} (${f.civId}, ${f.tech ?? 'national church'}, t${f.turn})`).join('; ') || 'none'}; followers@150=${rel.followersAt150}/${rel.citiesAt150} cities; missionaries=${rel.missionaries} (conversions by them ${rel.missionaryConversions}, all ${rel.conversions})`);
    report(`  ROADS tiles@100 ${r.civs.map((c) => `${c.civId}:${c.roadsAt[100] ?? '-'}`).join(' ')}; @200 ${r.civs.map((c) => `${c.civId}:${c.roadsAt[200] ?? '-'}`).join(' ')}`);
  }
  const alive = all;
  const med = (k: string) => medianTurn(alive.map((c) => c.eraTurn[k]));
  const avg = (t: number) => (all.reduce((a, c) => a + (c.techsAt[t] ?? 0), 0) / all.length).toFixed(1);
  const first = (k: string) => Math.min(...all.map((c) => c.eraTurn[k] ?? Infinity));
  report(`FIRST medieval=${first('medieval')} industrial=${first('industrial')} modern=${first('modern')} tree=${Math.min(...all.map((c) => c.treeDoneTurn ?? Infinity))}; per seed tree=${seedTree.join(',')}`);
  report(`MEDIAN medieval=${med('medieval')} industrial=${med('industrial')} modern=${med('modern')} tree=${medianTurn(all.map(c=>c.treeDoneTurn))}`);
  report(`AVG techs t25=${avg(25)} t50=${avg(50)} t100=${avg(100)} t150=${avg(150)} t200=${avg(200)} t250=${avg(250)}`);
  report(`PER GAME wars=${wars/5} peace=${peace/5} elim=${elim/5}; avg cities end=${(all.reduce((a,c)=>a+c.cities,0)/all.length).toFixed(1)}`);
  report(`VICTORIES\n  ${wins.join('\n  ')}`);
  const avg1 = (a: number[]) => (a.reduce((x, y) => x + y, 0) / Math.max(1, a.length)).toFixed(1);
  report(`NAVAL per game: overseas cities founded=${overseas / seeds.length} landings=${landings / seeds.length}; ships per civ t100=${avg1(ships100)} (max ${Math.max(...ships100)}) t200=${avg1(ships200)} (max ${Math.max(...ships200)})`);
  const sum = (k: string) => barbs.reduce((a, b) => a + b[k], 0) / barbs.length;
  report(`BARBARIANS per game: villages at start=${sum('villagesAtStart')} destroyed=${sum('villagesDestroyed')} settled=${sum('villagesSettled')} spawned=${sum('spawned')} killed=${sum('killed')} raids=${sum('raids')} eliminations by barbarians=${sum('eliminationsByBarbarians')} huts entered=${sum('hutsEntered')} artifacts=${sum('artifacts')}`);
  report(`AIR per game: strikes=${strikes / seeds.length} intercepts=${intercepts / seeds.length} city captures=${captures / seeds.length}; aircraft per civ at turn 220: avg ${avg1(air220)} (max ${Math.max(...air220)}); domination wins: ${wins.filter((w) => w.includes('domination')).length} of ${seeds.length}`);
  report(`GREAT PEOPLE per civ by turn 150: avg ${avg1(gp150)} (min ${Math.min(...gp150)}, max ${Math.max(...gp150)})`);
  report(`RELIGION per game: founded=${avg1(religionsPerGame)} (${religionsPerGame.join(',')}); cities following a religion at turn 150: ${followers150}/${cities150} (${((100 * followers150) / Math.max(1, cities150)).toFixed(0)}%); missionaries=${missionaries / seeds.length} (their conversions ${missionaryConv / seeds.length}, all conversions ${conversions / seeds.length})`);
  report(`ROADS per civ: tiles at turn 100 avg ${avg1(roads100)} (max ${Math.max(...roads100)}); at turn 200 avg ${avg1(roads200)} (max ${Math.max(...roads200)})`);
  report(`EARLIEST WIN: turn ${Math.min(...earliestWin)} (no win before 150: ${earliestWin.every((t) => t >= 150) ? 'yes' : 'NO'})`);
  const lm = landmassStats(100);
  report(`LANDMASSES (100 seeds): each civ alone=${lm.allSeparate} all on one=${lm.allTogether} shared/mixed=${lm.mixed}; distinct start landmasses 1..5=${lm.distinctStarts.join('/')}; empty island (room for a city)=${lm.emptyIsland} (room for 2+: ${lm.emptyBigIsland})`);
}, 600000);
